ForumWebsite/Models/Post.cs
using ForumWebsite.Models.Authentication;

namespace ForumWebsite.Models
{
    public class Post
    {
        public Post()
        {
            Comments = new HashSet<Comment>();
        }

        public long Id { get; set; }
        public string Header { get; set; } = null!;
        public string Body { get; set; } = null!;
        public DateTime CreatedTimestamp { get; set; }
        public bool IsClosed { get; set; }

        // Foreign keys
        public string UserId { get; set; } = null!;

        // References
        public virtual User User { get; set; } = null!;
        public virtual ICollection<Comment> Comments { get; set; } = null!;
    }
}

ForumWebsite/Models/ViewMoels/EditCommentViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ForumWebsite.Models.ViewMoels
{
    public class EditCommentViewModel
    {
        public long CommentId { get; set; }

        [Required]
        [StringLength(65535, ErrorMessage = "The comment must be between 10 and 65535 characters.", MinimumLength = 10)]
        [DataType(DataType.MultilineText)]
        [Display(Name = "Body")]
        public string Body { get; set; } = null!;
    }
}

ForumWebsite/Models/ViewMoels/EditPostViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ForumWebsite.Models.ViewMoels
{
    public class EditPostViewModel
    {
        public long PostId { get; set; }

        [Required]
        [StringLength(20, ErrorMessage = "The header must be between 5 and 20 characters.", MinimumLength = 5)]
        [DataType(DataType.Text)]
        [Display(Name = "Header")]
        public string Header { get; set; } = null!;

        [Required]
        [StringLength(65535, ErrorMessage = "The body of the post must be between 10 and 65535 characters.", MinimumLength = 10)]
        [DataType(DataType.MultilineText)]
        [Display(Name = "Body")]
        public string Body { get; set; } = null!;
    }
}

ForumWebsite/Models/ViewMoels/NewPostViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ForumWebsite.Models.ViewMoels
{
    public class NewPostViewModel
    {
        [Required]
        [StringLength(20, ErrorMessage = "The header must be between 5 and 20 characters.", MinimumLength = 5)]
        [DataType(DataType.Text)]
        [Display(Name = "Header")]
        public string Header { get; set; } = null!;

        [Required]
        [StringLength(65535, ErrorMessage = "The body of the post must be between 10 and 65535 characters.", MinimumLength = 10)]
        [DataType(DataType.MultilineText)]
        [Display(Name = "Body")]
        public string Body { get; set; } = null!;
    }
}

ForumWebsite/Models/ViewMoels/PostViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ForumWebsite.Models.ViewMoels
{
    public class PostViewModel
    {
        public Post? Post { get; set; }
        public List<Comment>? Comments { get; set; }

        [Required]
        [StringLength(65535, ErrorMessage = "The comment must be between 10 and 65535 characters.", MinimumLength = 10)]
        [DataType(DataType.MultilineText)]
        [Display(Name = "Body")]
        public string CommentBody { get; set; } = null!;
    }
}

ForumWebsite/Controllers/ForumController.cs
using ForumWebsite.Models;
using ForumWebsite.Models.Authentication;
using ForumWebsite.Models.ViewMoels;
using ForumWebsite.Services;
using ForumWebsite.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ForumWebsite.Controllers
{
    public class ForumController : Controller
    {
        private static readonly int PAGE_SIZE = 10;

        private readonly UserManager<User> _userManager;
        private readonly IPostService _postService;
        private readonly ICommentService _commentService;

        public ForumController(UserManager<User> userManager, IPostService postService, ICommentService commentService)
        {
            _userManager = userManager;
            _postService = postService;
            _commentService = commentService;
        }

        [HttpGet]
        public async Task<IActionResult> Index([FromQuery]int page)
        {
            List<Post> posts = await _postService.GetPostsPaginatedAsync(page, PAGE_SIZE);
            ViewBag.Page = page;

            if (User.Identity != null && User.Identity.IsAuthenticated)
            {
                User user = await _userManager.FindByNameAsync(User.Identity?.Name);
                if (user != null)
                {
                    ViewBag.CanDeletePost = await _userManager.IsInRoleAsync(user, StringLibrary.RoleNames.Admin);
                }
            }

            return View(posts);
        }

        [Authorize]
        [HttpGet]
        public IActionResult NewPost()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> NewPost(NewPostViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByNameAsync(User.Identity?.Name);
                if (user != null)
                {
                    Post? result = await _postService.CreatePostAsync(user, viewModel);
                    if (result != null)
                    {
                        return RedirectToAction("PostView", new { postId = result.Id });
                    }

                    ModelState.AddModelError(StringLibrary.PostErrors.NewPostFailCode, StringLibrary.PostErrors.NewPostFailDescription);
                }
                else
                {
                    ModelState.AddModelError(StringLibrary.PostErrors.UserNotFoundCode, StringLibrary.PostErrors.UserNotFoundDescription);
                }
            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> PostView([FromQuery]long postId)
        {
            Post? post = await _postService.GetPostAsync(postId);
            if (post != null)
            {
                if (User.Identity != null && User.Identity.IsAuthenticated)
                {
                    User user = await _userManager.FindByNameAsync(User.Identity.Name);
                    if (user != null)
                    {
                        ViewBag.CanEdit = await _userManager.IsInRoleAsync(user, StringLibrary.RoleNames.Admin) || await _userManager.IsInRoleAsync(user, StringLibrary.RoleNames.Moderator);
                    }
                }

                return View(new PostViewModel()
                {
                    Post = post,
                    Comments = await _commentService.GetAllCommentsAsync(postId)
                });
            }

            ModelState.AddModelError(StringLibrary.PostErrors.PostNotFoundCode, StringLibrary.PostErrors.PostNotFoundDescription);
            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> PostView([FromQuery]long postId, PostViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByNameAsync(User.Identity?.Name);
                if (user != null)
                {
                    Comment? comment = await _commentService.CreateCommentAsync(user, postId, viewModel);
                    if (comment != null)
                    {
                        return RedirectToAction("PostView", new { postId = postId });
                    }

                    ModelState.AddModelError(StringLibrary.PostErrors.NewCommentFailCode, StringLibrary.PostErrors.NewCommentFailDescription);
                }
                else
                {
                    ModelState.AddModelError(StringLibrary.PostErrors.UserNotFoundCode, StringLibrary.PostErrors.UserNotFoundDescription);
                }
            }

            return View();
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> EditPost([FromQuery]long postId)
        {
            User user = await _userManager.FindByNameAsync(User.Identity?.Name);
            if (user != null)
            {
                Post? post = await _postService.GetPostAsync(postId);
                if (post != null)
                {
                    if (post.UserId != user.Id && !await _userManager.IsInRoleAsync(user, StringLibrary.RoleNames.Admin) && !await _userManager.IsInRoleAsync(user, StringLibrary.RoleNames.Moderator))
                        return Redirect("/User/AccessDenied");

                    return View(new EditPostViewModel()
                    {
                        PostId = postId,
                        Header = post.Header,
                        Body = post.Body
                    });
                }
                else
                {
                    ModelState.AddModelError(StringLibrary.PostErrors.PostNotFoundCode, StringLibrary.PostErrors.PostNotFoundDescription);
                }
            }
            else
            {
                ModelState.AddModelError(StringLibrary.PostErrors.UserNotFoundCode, StringLibrary.PostErrors.UserNotFoundDescription);
            }

            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> EditPost([FromQuery]long postId, EditPostViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByNameAsync(User.Identity?.Name);
                if (user != null)
                {
                    Post? post = await _postService.GetPostAsync(postId);
                    if (post != null)
                    {
                        if (post.UserId != user.Id && !await _userManager.IsInRoleAsync(user, StringLibrary.RoleNames.Admin) && !await _userManager.IsInRoleAsync(user, StringLibrary.RoleNames.Moderator))
                            return Redirect("/User/AccessDenied");

                        if (await _postService.EditPostAsync(postId, viewModel))
                        {
                            return RedirectToAction("PostView", new { postId = postId });
                        }
                        else
                        {
                            ModelState.AddModelError(StringLibrary.PostErrors.EditPostFailCode, StringLibrary.PostErrors.EditPostFailDescription);
                        }
                    }
                    else
                    {
                        ModelState.AddModelError(StringLibrary.PostErrors.PostNotFoundCode, StringLibrary.PostErrors.PostNotFoundDescription);
                    }
                }
                else
                {
                    ModelState.AddModelError(StringLibrary.PostErrors.UserNotFoundCode, StringLibrary.PostErrors.UserNotFoundDescription);
                }
            }

            return View();
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> EditComment([FromQuery]long commentId)
        {
            User user = await _userManager.FindByNameAsync(User.Identity?.Name);
            if (user != null)
            {
                Comment? comment = await _commentService.GetCommentAsync(commentId);
                if (comment != null)
                {
                    if (comment.UserId != user.Id && !await _userManager.IsInRoleAsync(user, StringLibrary.RoleNames.Admin) && !await _userManager.IsInRoleAsync(user, StringLibrary.RoleNames.Moderator))
                        return Redirect("/User/AccessDenied");

                    return View(new EditCommentViewModel()
                    {
                        CommentId = commentId,
                        Body = comment.Body
                    });
                }
                else
                {
                    ModelState.AddModelError(StringLibrary.PostErrors.CommentNotFoundCode, StringLibrary.PostErrors.CommentNotFoundDescription);
                }
            }
            else
            {
                ModelState.AddModelError(StringLibrary.PostErrors.UserNotFoundCode, StringLibrary.PostErrors.UserNotFoundDescription);
            }

            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> EditComment([FromQuery]long commentId, EditCommentViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByNameAsync(User.Identity?.Name);
                if (user != null)
                {
                    Comment? comment = await _commentService.GetCommentAsync(commentId);
                    if (comment != null)
                    {
                        if (comment.UserId != user.Id && !await _userManager.IsInRoleAsync(user, StringLibrary.RoleNames.Admin) && !await _userManager.IsInRoleAsync(user, StringLibrary.RoleNames.Moderator))
                            return Redirect("/User/AccessDenied");

                        if (await _commentService.EditCommentAsync(commentId, viewModel))
                        {
                            return RedirectToAction("PostView", new { postId = comment.PostId });

ForumWebsite/Views/Forum/EditComment.cshtml
@model ForumWebsite.Models.ViewMoels.EditCommentViewModel

<h3>Edit Comment</h3>
<hr />

<form asp-action="EditComment" asp-route-commentId="@Model.CommentId">
    <table>
        <tr>
            <td colspan="3"><div asp-validation-summary="All"></div></td>
        </tr>

        <tr>
            <td><label asp-for="Body"></label></td>
            <td><textarea asp-for="Body" style="resize:none" cols="30" rows="5"></textarea></td>
            <td><span asp-validation-for="Body"></span></td>
        </tr>
        <tr>
            <td colspan="3"><input type="submit" value="Save" /></td>
        </tr>
    </table>
</form>

@section scripts{
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}

ForumWebsite/Views/Forum/EditPost.cshtml
@model ForumWebsite.Models.ViewMoels.EditPostViewModel

<h3>Edit Post</h3>
<hr />

<form asp-action="EditPost" asp-route-postId="@Model.PostId">
    <table>
        <tr>
            <td colspan="3"><div asp-validation-summary="All"></div></td>
        </tr>

        <tr>
            <td><label asp-for="Header"></label></td>
            <td><input asp-for="Header" /></td>
            <td><span asp-validation-for="Header"></span></td>
        </tr>
        <tr>
            <td><label asp-for="Body"></label></td>
            <td><textarea asp-for="Body" style="resize:none" cols="18" rows="20"></textarea></td>
            <td><span asp-validation-for="Body"></span></td>
        </tr>
        <tr>
            <td colspan="3"><input type="submit" value="Save" /></td>
        </tr>
    </table>
</form>

@section scripts{
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}

ForumWebsite/Views/Forum/Index.cshtml
@model List<ForumWebsite.Models.Post>

<h3>Forum</h3>
<hr />

@if (User.Identity != null && User.Identity.IsAuthenticated)
{
    <h6><a class="nav-link text-dark" asp-area="" asp-controller="Forum" asp-action="NewPost">New Post</a></h6>
    <hr />
}

@if (Model == null || Model.Count == 0)
{
    <h5>There is no post.</h5>
}
else
{
    <table>
        <tr>
            <td class="text-dark">Header</td>
            <td class="text-dark">User</td>
            <td class="text-dark">Closed</td>
            @if (ViewBag.CanDeletePost != null && ViewBag.CanDeletePost)
            {
                <td class="text-dark">Delete Post</td>
                <td class="text-dark">Close Post</td>
            }
        </tr>
        @foreach (var post in Model)
        {
            <tr>
                <td><a class="nav-link text-dark" asp-area="" asp-controller="Forum" asp-action="PostView" asp-route-postId="@post.Id">@post.Header</a></td>
                <td>@post.User.UserName</td>
                <td>@post.IsClosed</td>
                @if (ViewBag.CanDeletePost != null && ViewBag.CanDeletePost)
                {
                    <td><a class="nav-link text-dark" asp-area="" asp-controller="Forum" asp-action="DeletePost" asp-route-postId="@post.Id" asp-route-returnPage="@ViewBag.Page">Delete</a></td>
                    <td><a class="nav-link text-dark" asp-area="" asp-controller="Forum" asp-action="ClosePost" asp-route-postId="@post.Id" asp-route-returnPage="@ViewBag.Page">Close</a></td>
                }
            </tr>
        }
    </table>

    <input type="button" value="Previous" onclick="location.href='@Url.Action("Index", "Forum", new { page = (int.Parse(ViewBag.Page.ToString()) - 1) })'" />
    @ViewBag.Page
    <input type="button" value="Next" onclick="location.href='@Url.Action("Index", "Forum", new { page = (int.Parse(ViewBag.Page.ToString()) + 1) })'" />
}

ForumWebsite/Views/Forum/NewPost.cshtml
@model ForumWebsite.Models.ViewMoels.NewPostViewModel

<h3>New Post</h3>
<hr />

<form asp-action="NewPost">
    <table>
        <tr>
            <td colspan="3"><div asp-validation-summary="All"></div></td>
        </tr>

        <tr>
            <td><label asp-for="Header"></label></td>
            <td><input asp-for="Header" /></td>
            <td><span asp-validation-for="Header"></span></td>
        </tr>
        <tr>
            <td><label asp-for="Body"></label></td>
            <td><textarea asp-for="Body" style="resize:none" cols="18" rows="20"></textarea></td>
            <td><span asp-validation-for="Body"></span></td>
        </tr>
        <tr>
            <td colspan="3"><input type="submit" value="Create" /></td>
        </tr>
    </table>
</form>

@section scripts{
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}

ForumWebsite/Views/Forum/PostView.cshtml
@model ForumWebsite.Models.ViewMoels.PostViewModel

@if (User.Identity != null && (Model.Post?.User.UserName == User.Identity.Name || (ViewBag.CanEdit != null && ViewBag.CanEdit)) && !Model.Post.IsClosed)
{
    <h6><a class="nav-link text-dark" asp-area="" asp-controller="Forum" asp-action="EditPost" asp-route-postId="@Model.Post?.Id">Edit Post</a></h6>
    <hr />
}

<h4>@Model.Post?.Header</h4>
<br />
@Model.Post?.Body

@if (User.Identity != null && User.Identity.IsAuthenticated && !Model.Post.IsClosed)
{
    <hr />
    <h5>Comment on this post:</h5>

    <form asp-action="PostView" asp-route-postId="@Model.Post?.Id">
        <table>
            <tr>
                <td colspan="3"><div asp-validation-summary="All"></div></td>
            </tr>
            <tr>
                <td><label asp-for="CommentBody"></label></td>
                <td><textarea asp-for="CommentBody" style="resize:none" cols="30" rows="5"></textarea></td>
                <td><span asp-validation-for="CommentBody"></span></td>
            </tr>
            <tr>
                <td colspan="3"><input type="submit" value="Send" /></td>
            </tr>
        </table>
    </form>
}

@if (Model.Post.IsClosed)
{
    <hr />
    <h5>This post is closed.</h5>
}
else if (Model.Comments == null || Model.Comments.Count == 0)
{
    <hr />
    <h5>There is no comment on this post.</h5>
}
else
{
    @foreach (var comment in Model.Comments)
    {
        <hr />
        <div>
            @comment.User.UserName said:
            <br />
            @comment.Body
            <br />
            @if (ViewBag.CanEdit != null && ViewBag.CanEdit && !Model.Post.IsClosed)
            {
                <a class="nav-link text-dark" asp-area="" asp-controller="Forum" asp-action="EditComment" asp-route-commentId="@comment.Id">Edit Comment</a>
                <a class="nav-link text-dark" asp-area="" asp-controller="Forum" asp-action="DeleteComment" asp-route-commentId="@comment.Id" asp-route-returnPostId="@Model.Post.Id">Delete Comment</a>
            }
            else if (User.Identity != null && comment.User.UserName == User.Identity.Name && !Model.Post.IsClosed)
            {
                <a class="nav-link text-dark" asp-area="" asp-controller="Forum" asp-action="EditComment" asp-route-commentId="@comment.Id">Edit Comment</a>
            }
        </div>
    }
}